#
# COPYRIGHT Ericsson 2023
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "eric-oss-5gpmevt-filetx-proc.fullname" . }}-pre-delete-job
  labels:
    {{- include "eric-oss-5gpmevt-filetx-proc.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": "before-hook-creation"
    {{- include "eric-oss-5gpmevt-filetx-proc.annotations" . | nindent 4 }}
spec:
  backoffLimit: 6
  template:
    metadata:
      annotations:
        {{- include "eric-oss-5gpmevt-filetx-proc.service-mesh-inject" . | nindent 8 }}
        {{- include "eric-oss-5gpmevt-filetx-proc.service-mesh-version" . | nindent 8 }}
        {{- include "eric-oss-5gpmevt-filetx-proc.istio-proxy-config-annotation" . | nindent 8 }}
        {{- include "eric-oss-5gpmevt-filetx-proc.annotations" . | nindent 8 }}
      labels:
        {{- include "eric-oss-5gpmevt-filetx-proc.service-mesh-inject" . | nindent 8 }}
        {{- include "eric-oss-5gpmevt-filetx-proc.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "eric-oss-5gpmevt-filetx-proc.fullname" . }}
      restartPolicy: Never
      imagePullSecrets:
        - name: {{ include "eric-oss-5gpmevt-filetx-proc.pullSecret" . | quote}}
      containers:
        - name: eric-oss-5gpmevt-pre-delete
          image: {{ template "eric-oss-5gpmevt-filetx-proc.imagePath" . }}
          imagePullPolicy: {{ template "eric-oss-5gpmevt-filetx-proc.registryImagePullPolicy" . }}
          env:
            - name: FIVEGPMEVENT_SERVICE_NAME
              value: {{ include "eric-oss-5gpmevt-filetx-proc.fullname" . }}
            - name: FIVEGPMEVENT_SERVICE_PORT
              value: {{ .Values.service.port | quote }}
          command: ["/bin/sh","-c"]
          args:
          - |
            "echo 'Delete Data Service Started http://${FIVEGPMEVENT_SERVICE_NAME}:FIVEGPMEVENT_SERVICE_PORT/' && 
                  deregister_response=$(echo $(curl -X DELETE http://${FIVEGPMEVENT_SERVICE_NAME}:${FIVEGPMEVENT_SERVICE_PORT}/data-service-instance | jq .))  && 
                  deregister_status=$(echo $deregister_response | jq .deregisterStatus) && 
                  echo -e '\n Delete Data Service Completed. \n' $deregister_response && 
                  exit $deregister_status "

            {{- include "eric-oss-5gpmevt-filetx-proc.service-mesh-sidecar-quit" .| nindent 12 }}
          resources:
            requests:
              cpu: {{ (index .Values "resources" "eric-oss-5gpmevt-filetx-proc-hooks" "requests" "cpu" | quote) }}
              memory: {{ (index .Values "resources" "eric-oss-5gpmevt-filetx-proc-hooks" "requests" "memory" | quote) }}
              ephemeral-storage: {{ (index .Values "resources" "eric-oss-5gpmevt-filetx-proc-hooks" "requests" "ephemeral-storage" | quote) }}
            limits:
              cpu: {{ (index .Values "resources" "eric-oss-5gpmevt-filetx-proc-hooks" "limits" "cpu" | quote) }}
              memory: {{ (index .Values "resources" "eric-oss-5gpmevt-filetx-proc-hooks" "limits" "memory" | quote) }}
              ephemeral-storage: {{ (index .Values "resources" "eric-oss-5gpmevt-filetx-proc-hooks" "limits" "ephemeral-storage" | quote) }}
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - all
            {{- include "eric-oss-5gpmevt-filetx-proc.seccomp-profile" . | indent 12 }}
      priorityClassName: {{ (index .Values "podPriority" "eric-oss-5gpmevt-filetx-proc" "priorityClassName") }}
      tolerations: {{- include "eric-oss-5gpmevt-filetx-proc.tolerations" . | nindent 8 }}
      nodeSelector: {{- include "eric-oss-5gpmevt-filetx-proc.nodeSelector" . | nindent 6 -}}