{
 "title": "eric-oss-5gpmevt-filetx-proc Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  { "title": "Kubernetes metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU: POC pod",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{pod=~\".*5gpmevt.*\", namespace=\"$Namespace\", container!=\"\"}[180s])",
     "legendFormat": "CUR: {{pod}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits{pod=~\".*5gpmevt.*\", container!=\"\", resource=\"cpu\" , namespace=\"$Namespace\"})",
     "legendFormat": "LIM: {{pod}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{pod=~\".*5gpmevt.*\", container!=\"\", resource=\"cpu\" , namespace=\"$Namespace\"})",
     "legendFormat": "REQ: {{pod}}"
    }
   ]
  },
  {
   "title": "Memory: POC pod",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{pod=~\".*5gpmevt.*\", image!=\"\", container!=\"\", container_name!=\"POD\", namespace=\"$Namespace\"}",
     "legendFormat": "CUR: {{pod}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits{pod=~\".*5gpmevt.*\", container!=\"\", resource=\"memory\" , namespace=\"$Namespace\"})",
     "legendFormat": "LIM: {{ pod }}"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{pod=~\".*5gpmevt.*\",  container!=\"\", resource=\"memory\", namespace=\"$Namespace\"})",
     "legendFormat": "REQ: {{pod}}"
    }
   ]
  },
  { "title": "Custom Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Number of Successfully Downloaded",
   "type": "timeseries",
   "description": "The number of files that have successfully downloaded from the SFTP Server ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "eric_oss_5gpmevt_filetx_proc:num_successful_file_transfer_total{namespace=\"$Namespace\", pod=~\".*5gpmevt.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Volume of Downloaded File Data",
   "type": "gauge",
   "description": "Volume of file data downloaded from SFTP Server",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eric_oss_5gpmevt_filetx_proc:transferred_file_data_volume{namespace=\"$Namespace\", pod=~\".*5gpmevt.*\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Number of Processed 5G Event Files",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "eric_oss_5gpmevt_filetx_proc:event_files_processed_total{namespace=\"$Namespace\", pod=~\".*5gpmevt.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Data Volume of Processed 5G Event Files",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "eric_oss_5gpmevt_filetx_proc:processed_file_data_volume{namespace=\"$Namespace\", pod=~\".*5gpmevt.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Number of Files Failed to Download ",
   "type": "timeseries",
   "description": "The number of files that have failed to download from the SFTP Server ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "eric_oss_5gpmevt_filetx_proc:num_failed_file_transfer_total{namespace=\"$Namespace\", pod=~\".*5gpmevt.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Kafka Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Input Topic: Messages read",
   "type": "timeseries",
   "description": "Input topic is of pattern \"file-notification-service--5g-event--.*\"",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_records_consumed_total{topic=~\"file-notification-service--5g-event--.*\", namespace=\"$Namespace\", pod!=\"\"}",
     "legendFormat": "{{pod}}: {{spring_id}}"
    },
    {
     "expr": "sum(kafka_consumer_fetch_manager_records_consumed_total{topic=~\"file-notification-service--5g-event--.*\", namespace=\"$Namespace\",pod!=\"\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Output Topic: Messages outputted",
   "type": "timeseries",
   "description": "Messages output to the output topics by topic and total",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(kafka_producer_topic_record_send_total{namespace=\"$Namespace\", pod!=\"\"}) by (topic)",
     "legendFormat": "{{topic}}"
    },
    {
     "expr": "sum(kafka_producer_topic_record_send_total{namespace=\"$Namespace\", pod!=\"\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Producer record size average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kafka_producer_record_size_avg{namespace=\"$Namespace\", pod!=\"\"}",
     "legendFormat": "{{pod}}: {{spring_id}}"
    }
   ]
  },
  {
   "title": "Producer Buffer Available",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kafka_producer_buffer_available_bytes{pod=~\".*5gpmevt.*\", namespace=\"$Namespace\"}",
     "legendFormat": "{{pod}}: {{spring_id}}"
    }
   ]
  },
  {
   "title": "Producer batch size average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kafka_producer_batch_size_avg{pod=~\".*5gpmevt.*\", namespace=\"$Namespace\"}",
     "legendFormat": "{{pod}}: {{spring_id}}"
    },
    {
     "expr": "sum(kafka_producer_batch_size_avg{pod=~\".*5gpmevt.*\", namespace=\"$Namespace\"}) by (pod)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Consumer fetch records per request average",
   "type": "timeseries",
   "description": "The average number of records in each request",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_records_per_request_avg{topic=~\"file-notification-service--5g-event--.*\", pod!=\"\", namespace=\"$Namespace\"}",
     "legendFormat": "{{pod}}: {{topic}}: {{spring_id}}"
    }
   ]
  },
  { "title": "JVM Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Heap Memory Used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{pod=~\".*5gpmevt.*\", namespace=\"$Namespace\"}",
     "legendFormat": "{{pod}}: {{id}}"
    }
   ]
  },
  {
   "title": "GC Pause Seconds Max",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(jvm_gc_pause_seconds_max{namespace=\"$Namespace\", pod=~\".*5gpmevt.*\"}[2m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Live Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{namespace=\"$Namespace\", pod=~\".*5gpmevt.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Daemon Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "targets": [
    {
     "expr": "jvm_threads_daemon_threads{namespace=\"$Namespace\", pod=~\".*5gpmevt.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Peak Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "targets": [
    {
     "expr": "jvm_threads_peak_threads{namespace=\"$Namespace\", pod=~\".*5gpmevt.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Thread States",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "targets": [
    {
     "expr": "jvm_threads_states_threads{namespace=\"$Namespace\", pod=~\".*5gpmevt.*\"}",
     "legendFormat": "{{pod}}: {{state}}"
    }
   ]
  }
 ]
}