#
# COPYRIGHT Ericsson 2023
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

{{- $serviceMesh := include "eric-oss-5gpmevt-filetx-proc.service-mesh-enabled" . | trim -}}
{{- $tls := include "eric-oss-5gpmevt-filetx-proc.global-security-tls-enabled" . | trim -}}
{{- if and (eq $serviceMesh "true") (eq $tls "true") }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: {{ template "eric-oss-5gpmevt-filetx-proc.name" . }}
  labels:
    {{- $kafkaClusterLabel := include "eric-oss-5gpmevt-filetx-proc.kafka-cluster-label" . | fromYaml }}
    {{- $labels := include "eric-oss-5gpmevt-filetx-proc.labels" . | fromYaml }}
    {{- include "eric-oss-5gpmevt-filetx-proc.mergeLabels" (dict "location" .Template.Name "sources" (list $kafkaClusterLabel $labels)) | nindent 8 }}
  annotations:
    {{- include "eric-oss-5gpmevt-filetx-proc.annotations" . | nindent 4 }}
spec:
  authentication:
    type: tls-external
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: '*'
          patternType: literal
        operation: Write
      - resource:
          type: transactionalId
          name: '*'
          patternType: literal
        operation: Write
      - resource:
          type: transactionalId
          name: '*'
          patternType: literal
        operation: Describe
      - resource:
          type: topic
          name: '*'
          patternType: literal
        operation: Read
      - resource:
          type: topic
          name: '*'
          patternType: literal
        operation: Create
      - resource:
          type: topic
          name: '*'
          patternType: literal
        operation: Alter
      - resource:
          type: topic
          name: '*'
          patternType: literal
        operation: AlterConfigs
      - resource:
          type: topic
          name: '*'
          patternType: literal
        operation: DescribeConfigs
      - resource:
          type: cluster
        operation: Create
      - resource:
          type: cluster
        operation: DescribeConfigs
      - resource:
          type: group
          name: '*'
          patternType: literal
        operation: Read
  {{- end }}